container:
  cfdna_wgs: "${HOME}/sing_containers/cfdna_wgs.1.0.0.sif"

dir:
  data:
    cfdna_wgs: "test"
  repo:
    cfdna_wgs: "/home/jeszyman/repos/cfdna-frag"
  scripts:
    cfdna_wgs: "workflow/scripts"

files:
  cfdna_wgs_frag_keep_bed: "test/inputs/keep.bed"
  cfdna_wgs_genome_fasta: "/mnt/ris/aadel/mpnst/inputs/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"

threads:
  cfdna_wgs: 4
